### ISSUE TITLE
create chroot_java.lst

### ISSUE THREAD

**Issue by abmusse** [IBM/ibmichroot#34]
**[Original report](https://bitbucket.org/litmis/ibmichroot/issue/34) by Aaron Bartell (Bitbucket: [aaronbartell](https://bitbucket.org/aaronbartell), GitHub: [aaronbartell](https://github.com/aaronbartell)).**

----------------------------------------

Have two separate requests to create an ibmichroot for Java.  Adding this issue so others know I am pursuing it.

**Comment by ThePrez** [comment]
We can't deliver this because of how JAva is architected. If Java becomes available in RPM form in the future, one would then just use `yum` or `-i` to accomplish this (see #55)
