### ISSUE TITLE
Have yum install when -i option is used occur after the chroot is setup

### ISSUE THREAD

**Issue by abmusse** [IBM/ibmichroot#55]
We include an option `-i` to install software into the chroot using yum.

With the current script this will occur [first](https://github.com/IBM/ibmichroot/blob/master/chroot_setup.sh#L406) before the chroot is setup.

I suspect this was done to allow users to install software into the chroot post chroot setup.

I think we should have [yumInstall](https://github.com/IBM/ibmichroot/blob/master/chroot_setup.sh#L283) function be called after chroot setup is complete.

If a user would like to install software into the chroot post setup we should suggest using

`yum --installroot=/QOpenSys/root_path install package` directly.

What are your thoughts  @ThePrez ?

**Comment by ThePrez** [comment]
I like the idea. What would the syntax look like to install multiple packages? Just use `-i` multiple times? (`-i nodejs10 -i python3\*`)

**Comment by abmusse** [comment]
> What would the syntax look like to install multiple packages? Just use -i multiple times? 

Currently yes same as how the [-g](https://github.com/IBM/ibmichroot#install-software-into-chroot) option is used.
