### ISSUE TITLE
Need to rebuild (or stop using) tar files

### ISSUE THREAD

**Issue by ThePrez** [IBM/ibmichroot#61]
I've run into several occasions where chroots were braindead, but it was remedied by running:
`rm -f /QOpenSys/pkgs/lib/ibmichroot/config/*.tar`
I suspect the .tar files get out of sync with the installed PASE version. I propose we rebuild the .tar files on every invocation and incur the performance overhead cost for the sake of usability.

**Comment by kadler** [comment]
My understanding is that the tar files are only there to speed up later invocations. If we're going to rebuild them everytime, there's no point to even creating them.

**Comment by abmusse** [comment]
Ok I will open a PR removing lines where we create the tar file and also check that it exists

**Comment by abmusse** [comment]
@kadler @ThePrez 

If we are no longer caching the created tar files

Then it looks like we wont need the [chroot_tar_dir](https://github.com/IBM/ibmichroot/blob/master/chroot_setup.sh#L89) function.

its used whenever `:tar_dir` is located in a `.lst`:

- [config/chroot_ZendDBi-5.1.59.lst](https://github.com/IBM/ibmichroot/blob/master/config/chroot_ZendDBi-5.1.59.lst#L15)
- [config/chroot_xlc.lst](https://github.com/IBM/ibmichroot/blob/master/config/chroot_xlc.lst#L14)
- [config/chroot_ZendServer6.lst](https://github.com/IBM/ibmichroot/blob/master/config/chroot_ZendServer6.lst#L19)
- [config/chroot_minimal.lst](https://github.com/IBM/ibmichroot/blob/master/config/chroot_minimal.lst#L445)
- [config/chroot_libs.lst](https://github.com/IBM/ibmichroot/blob/master/config/chroot_libs.lst#L18)
- [config/chroot_template.lst](https://github.com/IBM/ibmichroot/blob/master/config/chroot_template.lst#L66)
- [config/chroot_ZendServer5.lst](https://github.com/IBM/ibmichroot/blob/master/config/chroot_ZendServer5.lst#L15)
- [config/chroot_PowerRuby.lst](https://github.com/IBM/ibmichroot/blob/master/config/chroot_PowerRuby.lst#L15)
- [config/chroot_bins.lst](https://github.com/IBM/ibmichroot/blob/master/config/chroot_bins.lst#L18)
- [config/chroot_includes.lst](https://github.com/IBM/ibmichroot/blob/master/config/chroot_includes.lst#L15)
- [config/chroot_nls.lst](https://github.com/IBM/ibmichroot/blob/master/config/chroot_nls.lst#L14)
- [chroot_setup.sh](https://github.com/IBM/ibmichroot/blob/master/chroot_setup.sh#L228)

We can instead us [chroot_cp_dir](https://github.com/IBM/ibmichroot/blob/master/chroot_setup.sh#L82), which simply copies the target dir into the chroot.

Probably can just change all instances of `:tar_dir` in `.lst` files  -> `:cp_dir`.

Then we can safely remove the  [chroot_tar_dir](https://github.com/IBM/ibmichroot/blob/master/chroot_setup.sh#L89) function
