### ISSUE TITLE
How to remove chroot container - documentation

### ISSUE THREAD

**Issue by bimbra** [IBM/ibmichroot#65]
Creating a chroot container in IBM i IFS is well documented, but I am not seeing any steps to remove the chroot container. Is it a simple matter of doing recursive remove of the files and directories under 
/QOpenSys/<containername>

**Comment by abmusse** [comment]
Thats right just run `rm -r path_to_chroot`

**Comment by bimbra** [comment]
Thanks for the confirmation. 
A one line addition in chroot documentation will be ideal.
