### ISSUE TITLE
Update Resource links

### ISSUE THREAD

**Issue by thebeardedgeek** [IBM/ibmichroot#84]
[A (root) Change For The Better](http://bit.ly/ibmsystemsmag-chroot)

[A (root) Change for the Better (part II)](http://bit.ly/ism-chroot2)

are broken links and no longer work.

They can be updated to:
https://www.krengeltech.com/2016/01/a-root-change-for-the-better/
and
https://www.krengeltech.com/2016/02/a-root-change-for-the-better-part-ii/

**Comment by kadler** [comment]
Thanks for letting us know.
